(define (make-point x y)
  (cons x y))
(define (x-point p)
  (car p))
(define (y-point p)
  (cdr p))

(define (make-segment start end)
  (cons start end))
(define (start-segment s)
  (car s))
(define (end-segment s)
  (cdr s))

(define (midpoint-segment x)
  (let ((s-x (x-point (start-segment x)))
        (s-y (y-point (start-segment x)))
        (e-x (x-point (end-segment x)))
        (e-y (y-point (end-segment x))))
    (define (average x y) (/ (+ x y) 2))
    (make-point (average s-x e-x)
                (average s-y e-y))))

(define (print-point p)
  (newline)
  (display "(")
  (display (x-point p))
  (display ",")
  (display (y-point p))
  (display ")"))

(define a (make-segment (make-point -3 2)
                        (make-point 7 -1)))
